name: Construir y Desplegar - Proyecto PHP Clásico

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      # Se utiliza para obtener el código fuente del repositorio.

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Ajustar la versión de PHP según sea necesario.

    - name: Validar sintaxis de PHP
      run: |
        Get-ChildItem -Recurse -Filter *.php | ForEach-Object { php -l $_.FullName }
      # Verifica la sintaxis de todos los archivos PHP en el proyecto.

    - name: Listar archivos en el directorio biblioteca
      run: dir biblioteca
      # Muestra los archivos en el directorio biblioteca.

    - name: Listar archivos en el directorio Controller
      run: dir biblioteca\Controller
      # Muestra los archivos en el directorio Controller.

    - name: Mostrar contenido de Load.php
      run: Get-Content biblioteca\Libraries\Core\Load.php
      # Muestra el contenido del archivo Load.php para revisión.

    # Opcional: Ejecutar análisis estático de código con PHPStan
    # - name: Configurar PHPStan
    #   run: composer require --dev phpstan/phpstan
    # - name: Ejecutar PHPStan
    #   run: vendor\bin\phpstan analyse --level max

    # Opcional: Ejecutar pruebas unitarias
    # - name: Ejecutar pruebas unitarias
    #   run: phpunit --configuration phpunit.xml
