name: Semgrep Analysis

on: 
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Semgrep
      - name: Set up Semgrep
        run: docker pull semgrep/semgrep

      # Run Semgrep Scan and produce SARIF report
      - name: Run Semgrep
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off

      # Upload SARIF result to GitHub Code Scanning
      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

      # Run Semgrep Scan and produce JSON report
      - name: Run Semgrep for JSON Output
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --json --output semgrep.json --metrics=off

      # Install prospector-html
      - name: Install prospector-html
        run: python -m pip install prospector2html

      # Convert Semgrep JSON results to HTML
      - name: Convert Semgrep results to HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      # Create folder for reports
      - name: Move report to reports folder
        run: |
          mkdir -p reports  # Create directory if it doesn't exist
          mv semgrep-report.html reports/  # Move the HTML report to the reports folder
