name: Html

on: 
  push: 
    # Se activa el análisis en cada push al repositorio.

jobs:
  semgrep-analysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout del código
        uses: actions/checkout@v4

